### ISSUE TITLE
Disable backend CC submit button until ready

### ISSUE THREAD

**Issue by isaacfreeman** [solidusio/solidus_paypal_braintree#102]
JS handling the credit card form on the backend should ensure that the submit button is disabled until it's confirmed that the iframes are set up.

Without this, it's possible to submit the form before it's ready, especially during feature specs.

**Comment by seand7565** [comment]
Hey @isaacfreeman - sorry for the necro, trying to clear out old issues! For this issue: Thanks for the submission! It should be a simple fix but I'm not sure if it makes sense to implement - the fields load in very quickly, it would be hard for a human user to accidentally submit the form before the fields are loaded, and even then you'd just get an error message. For testing it's pretty simple to just wait until the fields are loaded before submitting - in fact, I think nowadays Capybara will wait until the fields are loaded before filling them in & continuing to submit, so I'd think it'd be pretty hard to trigger it with a test anyway.
