### ISSUE TITLE
Missing partial spree/admin/shared/preference_fields/_hash

### ISSUE THREAD

**Issue by afdev82** [solidusio/solidus_paypal_braintree#132]
I just installed the gem and follow the documentation to add a new payment method, but when I first save the method I get this error in the admin:
```
Missing partial spree/admin/shared/preference_fields/_hash
```
Yes, the partial is missing. I don't know how to solve this.

Latest gem and solidus v2.4.0

**Comment by tvdeyen** [comment]
Fixed by #136
