### ISSUE TITLE
No route if the engine is not mounted in Solidus path

### ISSUE THREAD

**Issue by afdev82** [solidusio/solidus_paypal_braintree#134]
I f I have solidus at `/store` for example, the default installer mounts the gem in `/solidus_paypal_braintree`.
In the js it doesn't find the right url to submit, it expects to be `/store/solidus_paypal_braintree`, because it uses the Spree helper `Spree.pathFor()` [here](https://github.com/solidusio/solidus_paypal_braintree/blob/517ec0c9b101d1f6e4d7fd44676a7264745bc292/app/assets/javascripts/solidus_paypal_braintree/constants.js#L6).
I solved mounting the engine in `/store/solidus_paypal_braintree`, maybe it could be useful to write a note in the README, or to change the default installer to mount the engine under the Solidus mount point, I don't know yet.

**Comment by asa644** [comment]
Hello @afdev82. I am facing the same problem you faced, I didn't quite get how did you solve it, Could you tell me how did you do it?

**Comment by tvdeyen** [comment]
Try mounting the solidus paypal braintree engine at the same mountpoint you mounted solidus

```rb
mount SolidusPaypalBraintree::Engine, at: '/your-mount-point/solidus_paypal_braintree'
```

Let me know if this helps

**Comment by afdev82** [comment]
@asa644 Yes, as tvdeyen already said, you have to mount the Engine under your mount point for Solidus
