### ISSUE TITLE
Missing partial spree/checkout/existing_payment/_paypal_braintree 

### ISSUE THREAD

**Issue by afdev82** [solidusio/solidus_paypal_braintree#135]
I get this if I try to order again.

Latest gem and solidus v2.4.0

**Comment by afdev82** [comment]
I solved adding a empty partial in `spree/checkout/existing_payment/_paypal_braintree.html.erb`.
I don't know if there is the possibility to show the last 4 digits of the credit card or the paypal account that was used before.

**Comment by mntmn** [comment]
Also just ran into this while testing checkout.

**Comment by tonydefaria** [comment]
I'm also getting this. However @afdev82 suggestion seems to "sort out" the issue.
I would also like to know if there is any possibility to show the last 4 digits of the last used credit card or paypal account.

**Comment by afdev82** [comment]
I managed to get the information using the response object from Braintree. This data is not stored in our database, but we have a token for each payment, in order to ask Braintree about that information:
```ruby
if payment.source.is_a?(SolidusPaypalBraintree::Source)
  if payment.source.credit_card?  
    payment.source.last_digits
  else
    ...
  end
end
```
