### ISSUE TITLE
ActiveRecord::SubclassNotFound after trying to save payment gateway record

### ISSUE THREAD

**Issue by digitalWestie** [solidusio/solidus_paypal_braintree#147]
I'm using solidus 2.4.2, and after installing gem from latest commit: 

`gem 'solidus_paypal_braintree', :git => 'https://github.com/solidusio/solidus_paypal_braintree.git', :ref => '898eb2cad5438f1540bf7cb636e90a24038ad4fb'`

I ran 

```
g = SolidusPaypalBraintree::Gateway.new(
  name: "Braintree",
  preference_source: "braintree_credentials"
)
g.save
```

and get:

```
ActiveRecord::SubclassNotFound: The single-table inheritance mechanism failed to locate the subclass: 'Solidus::Gateway::BraintreeGateway'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Spree::PaymentMethod.inheritance_column to use another column for that information.
```

Inspecting the object I see that `g.type` is `"SolidusPaypalBraintree::Gateway"` not `Solidus::Gateway::BraintreeGateway`

**Comment by digitalWestie** [comment]
Ah, figured it out. Nothing to do with this gem. Before installing this gem I tried out the [solidus_braintree](https://github.com/solidusio/solidus_braintree) gem and then deleted it. What I didn't realise was the payment method record still existed (as it was soft deleted) but the gateway class it was looking for no longer existed.

**Comment by gildardoperez** [comment]
@digitalWestie how did you solved deleting the gateway class? I'm getting

"ActiveRecord::SubclassNotFound (The single-table inheritance mechanism failed to locate the subclass: 'Solidus::Gateway::BraintreeGateway'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Spree::PaymentMethod.inheritance_column to use another column for that information.)"

**Comment by digitalWestie** [comment]
Hm I vaguely remember getting the same error. It might be the reason I had stick with an older version of the gem: 

`gem 'solidus_paypal_braintree', :git => 'https://github.com/solidusio/solidus_paypal_braintree.git', :ref => '898eb2cad5438f1540bf7cb636e90a24038ad4fb'`

**Comment by digitalWestie** [comment]
Do you have any records in the `spree_payment_methods` table in your db?  

I discovered I had a `payment_method` record that referred to a class that didn't exist anymore.

**Comment by gildardoperez** [comment]
@digitalWestie Hi, I found how to fix this issue. Thanks!

`
> rails console
> ActiveRecord::Base.connection.execute("DELETE FROM spree_payment_methods WHERE type='Solidus::Gateway::BraintreeGateway'")
`
