### ISSUE TITLE
Braintree Callback Webhooks Supported?

### ISSUE THREAD

**Issue by tblanchard** [solidusio/solidus_paypal_braintree#148]
https://developers.braintreepayments.com/guides/webhooks/overview

Lists a number of webhook callbacks that can be implemented to be notified about things like when a payment is disputed.

I do not find support in this code for webhook support.  Am I just missing that or do they just not exist?

**Comment by vokshirg** [comment]
@tblanchard have you found way how to use webhooks?

**Comment by kennyadsl** [comment]
They do not exist at the moment and I can't see in the list of webhooks any that we can actually use to change states or perform operations in Solidus. Closing this but let me know if I'm missing something.
