### ISSUE TITLE
Cancel PayPal order causes 500 error

### ISSUE THREAD

**Issue by prwhitehead** [solidusio/solidus_paypal_braintree#155]
When the admin tries to cancel an order, a 500 error is thrown. The reason is that `SolidusPaypalBraintree::Gateway.cancel` expects a response code string and is passed a `Spree::Payment` instance. 

I have created a PR here: https://github.com/solidusio/solidus_paypal_braintree/pull/154

**Comment by seand7565** [comment]
Looks like this issue was solved with https://github.com/solidusio/solidus_paypal_braintree/pull/173 🎉
