### ISSUE TITLE
Move from the deprecated paypal.js library to the current paypal-checkout.js library?

### ISSUE THREAD

**Issue by joshcampbell** [solidusio/solidus_paypal_braintree#157]
Background:

https://developers.braintreepayments.com/guides/paypal/vault/javascript/v3

The gem currently uses the old, deprecated `paypal` braintree library (https://js.braintreegateway.com/web/3.22.1/js/paypal.js). while current documentation only exists for the newer `paypal-checkout` library (https://js.braintreegateway.com/web/3.22.1/js/paypal-checkout.js).

Is someone at Solidus working on this already? Any insights as to when the deprecated library may actually stop working?

**Comment by tvdeyen** [comment]
I am currently looking into this

**Comment by seantaylor** [comment]
@tvdeyen If we're going to be moving from the `paypal.js` to the newer `paypal-checkout.js` it may also be a good time to upgrade from `3.22.1` to the latest? https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md. Looks like some good bug fixes in there.

**Comment by alepore** [comment]
This was done on #170
