### ISSUE TITLE
Solidus 2.6 requires spree/api/payments/source_views/_paypal_braintree.json.jbuilder

### ISSUE THREAD

**Issue by octave** [solidusio/solidus_paypal_braintree#167]
When using solidus 2.6.0rc1, when viewing the shipment tab of an order in the admin in generate an error:

```
ActionView::Template::Error (Missing partial spree/api/payments/source_views/_paypal_braintree with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:jbuilder]}
```
```
    34:     payment_source = payment.source.is_a?(Spree::Payment) ? payment.source.source : payment.source
    35: 
    36:     if payment_source
    37:       json.partial!(
    38:         "spree/api/payments/source_views/#{payment.payment_method.partial_name}",
    39:         payment_source: payment_source
    40:       )
```

It seems to be coming from this change to `solidus`: https://github.com/solidusio/solidus/commit/6bbe885b556ebccccad228509ffdcd1ea1e12e8e#diff-44ad61de10149fd0c31668436c9b273b

**Comment by prwhitehead** [comment]
To sidestep this issue, I added the following to `app/views/spree/api/payments/source_views/_paypal_braintree.json.jbuilder`: 

    json.(payment_source, *%i(payment_type))

**Comment by ychaker** [comment]
had the same issue, thank you @prwhitehead for the heads up and the solution. life saver!
