### ISSUE TITLE
Creditcard fields are readonly

### ISSUE THREAD

**Issue by johvo** [solidusio/solidus_paypal_braintree#171]
I have tried to integrate solidus_paypal_braintree to my shop but I can't enter values to the textboxes for creditcard. It works fine for the name but not for the rest.

Does anyone know this problem or had similar issues?

![braintree_read_only](https://user-images.githubusercontent.com/1787893/41485653-bf3cf784-70e1-11e8-9f07-72e71c0c718f.png)

**Comment by ychaker** [comment]
@johvo did you ever figure this one out?
