### ISSUE TITLE
Unable to set preference source

### ISSUE THREAD

**Issue by RWSDev** [solidusio/solidus_paypal_braintree#194]
when I create new payment method:

I can set type to Braintree.  However I cannot change "Preference Source" to Braintree_credentials as stated in the readme.  the only option available is (custom).

**Comment by seand7565** [comment]
Hey there @RWSDev ! You've probably moved on from this issue, but just for posterity: 
If you don't see the payment source available, it probably hasn't been set up right in the initializer. You can find that process documented [here](https://github.com/solidusio/solidus_paypal_braintree/blob/bf5fe0e154d38f7c498f1c54450bb4de7608ff04/README.md#create-a-new-payment-method).
