### ISSUE TITLE
when only using PayPal  invalid address on return

### ISSUE THREAD

**Issue by RWSDev** [solidusio/solidus_paypal_braintree#195]
When I'm using PayPal only for checkout everything goes correctly until return then I receive a flash message stating "invalid address" and the order does not go through.  Also, noticed in the database for spree_addresses table, the state field is always NULL.  Not sure if this is related or not.

below is output from return that fails:

`  ↳ /Users/crypt3ch/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/solidus_paypal_braintree-dbcee4ec1b09/app/controllers/solidus_paypal_braintree/client_tokens_controller.rb:17
  Spree::PaymentMethod Exists (1.6ms)  SELECT  1 AS one FROM `spree_payment_methods` INNER JOIN `spree_store_payment_methods` ON `spree_payment_methods`.`id` = `spree_store_payment_methods`.`payment_method_id` WHERE `spree_payment_methods`.`deleted_at` IS NULL AND `spree_store_payment_methods`.`store_id` = 1 LIMIT 1
  ↳ /Users/crypt3ch/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/solidus_paypal_braintree-dbcee4ec1b09/app/controllers/solidus_paypal_braintree/client_tokens_controller.rb:17
   (1.0ms)  SELECT `spree_payment_methods`.`id` FROM `spree_payment_methods` INNER JOIN `spree_store_payment_methods` ON `spree_payment_methods`.`id` = `spree_store_payment_methods`.`payment_method_id` WHERE `spree_payment_methods`.`deleted_at` IS NULL AND `spree_store_payment_methods`.`store_id` = 1
  ↳ /Users/crypt3ch/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/solidus_paypal_braintree-dbcee4ec1b09/app/controllers/solidus_paypal_braintree/client_tokens_controller.rb:17
  SolidusPaypalBraintree::Gateway Load (0.5ms)  SELECT  `spree_payment_methods`.* FROM `spree_payment_methods` WHERE `spree_payment_methods`.`active` = TRUE AND `spree_payment_methods`.`type` IN ('SolidusPaypalBraintree::Gateway') AND `spree_payment_methods`.`deleted_at` IS NULL AND `spree_payment_methods`.`id` = 4 ORDER BY `spree_payment_methods`.`id` ASC LIMIT 1
  ↳ /Users/crypt3ch/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/solidus_paypal_braintree-dbcee4ec1b09/app/controllers/solidus_paypal_braintree/client_tokens_controller.rb:18
D, [2018-11-08T15:58:59.116393 #50061] DEBUG -- : [Braintree] [08/Nov/2018 21:58:59 UTC] POST /merchants/yk3qyqt2ygxhm6vx/client_token
D, [2018-11-08T15:58:59.116456 #50061] DEBUG -- : [Braintree] <?xml version="1.0" encoding="UTF-8"?>
[Braintree] <client-token>
[Braintree]   <version type="integer">2</version>
[Braintree] </client-token>

I, [2018-11-08T15:58:59.419133 #50061]  INFO -- : [Braintree] [08/Nov/2018 21:58:59 UTC] POST /merchants/yk3qyqt2ygxhm6vx/client_token 201
D, [2018-11-08T15:58:59.419181 #50061] DEBUG -- : [Braintree] [08/Nov/2018 21:58:59 UTC] 201 Created
D, [2018-11-08T15:58:59.419314 #50061] DEBUG -- : [Braintree] <?xml version="1.0" encoding="UTF-8"?>
[Braintree] <client-token>
[Braintree]   <value>eyJ2ZXJzaW9uIjoyLCJhdXRob3JpemF0aW9uRmluZ2VycHJpbnQiOiI1ZjA3MmQ1MGUxM2VjZGM4ZjE2YzA4YjQ3YTVjMzFjOWJjMWI3ODI4MDBlNjc3ZDhiYmI2MTM4ZjA1NjdhNTk5fGNyZWF0ZWRfYXQ9MjAxOC0xMS0wOFQyMTo1ODo1OS4yMzcxNzY0MDIrMDAwMFx1MDAyNm1lcmNoYW50X2lkPXlrM3F5cXQyeWd4aG02dnhcdTAwMjZwdWJsaWNfa2V5PWRiZGZwMm5iOWYyaGdyc3MiLCJjb25maWdVcmwiOiJodHRwczovL2FwaS5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tOjQ0My9tZXJjaGFudHMveWszcXlxdDJ5Z3hobTZ2eC9jbGllbnRfYXBpL3YxL2NvbmZpZ3VyYXRpb24iLCJncmFwaFFMIjp7InVybCI6Imh0dHBzOi8vcGF5bWVudHMuc2FuZGJveC5icmFpbnRyZWUtYXBpLmNvbS9ncmFwaHFsIiwiZGF0ZSI6IjIwMTgtMDUtMDgifSwiY2hhbGxlbmdlcyI6W10sImVudmlyb25tZW50Ijoic2FuZGJveCIsImNsaWVudEFwaVVybCI6Imh0dHBzOi8vYXBpLnNhbmRib3guYnJhaW50cmVlZ2F0ZXdheS5jb206NDQzL21lcmNoYW50cy95azNxeXF0MnlneGhtNnZ4L2NsaWVudF9hcGkiLCJhc3NldHNVcmwiOiJodHRwczovL2Fzc2V0cy5icmFpbnRyZWVnYXRld2F5LmNvbSIsImF1dGhVcmwiOiJodHRwczovL2F1dGgudmVubW8uc2FuZGJveC5icmFpbnRyZWVnYXRld2F5LmNvbSIsImFuYWx5dGljcyI6eyJ1cmwiOiJodHRwczovL29yaWdpbi1hbmFseXRpY3Mtc2FuZC5zYW5kYm94LmJyYWludHJlZS1hcGkuY29tL3lrM3F5cXQyeWd4aG02dngifSwidGhyZWVEU2VjdXJlRW5hYmxlZCI6dHJ1ZSwicGF5cGFsRW5hYmxlZCI6dHJ1ZSwicGF5cGFsIjp7ImRpc3BsYXlOYW1lIjoiSklUVCBIb2xkaW5ncyBJbmMuIiwiY2xpZW50SWQiOiJBUUo4dnZ3MjQtMDZRMk5fM3dGWU14R1BaVGZXd3NmejRPMEx5Z1JOQ3lpNmp4a3dVNTRJNzZjZGVQb3MxNEpkWFNQZmhLQjVodUdZaWlSeSIsInByaXZhY3lVcmwiOiJodHRwOi8vZXhhbXBsZS5jb20vcHAiLCJ1c2VyQWdyZWVtZW50VXJsIjoiaHR0cDovL2V4YW1wbGUuY29tL3RvcyIsImJhc2VVcmwiOiJodHRwczovL2Fzc2V0cy5icmFpbnRyZWVnYXRld2F5LmNvbSIsImFzc2V0c1VybCI6Imh0dHBzOi8vY2hlY2tvdXQucGF5cGFsLmNvbSIsImRpcmVjdEJhc2VVcmwiOm51bGwsImFsbG93SHR0cCI6dHJ1ZSwiZW52aXJvbm1lbnROb05ldHdvcmsiOmZhbHNlLCJlbnZpcm9ubWVudCI6Im9mZmxpbmUiLCJ1bnZldHRlZE1lcmNoYW50IjpmYWxzZSwiYnJhaW50cmVlQ2xpZW50SWQiOiJtYXN0ZXJjbGllbnQzIiwiYmlsbGluZ0FncmVlbWVudHNFbmFibGVkIjp0cnVlLCJtZXJjaGFudEFjY291bnRJZCI6ImppdHRob2xkaW5nc2luYyIsImN1cnJlbmN5SXNvQ29kZSI6IlVTRCJ9LCJtZXJjaGFudElkIjoieWszcXlxdDJ5Z3hobTZ2eCIsInZlbm1vIjoib2ZmIn0=</value>
[Braintree] </client-token>

Completed 200 OK in 573ms (Views: 0.6ms | ActiveRecord: 8.7ms)`

**Comment by dustineichler** [comment]
see filing an issue guide:
https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#filing-an-issue

**Comment by asa644** [comment]
@RWSDev did you have any luck?

**Comment by kennyadsl** [comment]
Closing, see #218
