### ISSUE TITLE
Random Travis CI Failures

### ISSUE THREAD

**Issue by skukx** [solidusio/solidus_paypal_braintree#215]
Starting a fresh branch from master where the only changes were adding a dependency, Travis CI fails. This has happened to several other branches as well.

See: https://travis-ci.org/solidusio/solidus_paypal_braintree/builds/488609105?utm_source=github_status&utm_medium=notification

```
NoMethodError:
  undefined method 'iso' in 'country' factory
```

The added code has no affect on what would cause an error like this.

**Comment by seand7565** [comment]
Hey @skukx thanks for the issue! Sorry for being a year and a half late to the party. As far as I can tell, this doesn't appear to be an issue anymore.
