### ISSUE TITLE
Paypal payment return invalid address

### ISSUE THREAD

**Issue by asa644** [solidusio/solidus_paypal_braintree#218]
Hello everyone! I want to start by thanking everyone who have put effort in this gem. 
I am using the latest solidus for an Ecommerce website and my rails version is 5.2.0, ruby is 2.6. 

I am being directed to PayPal successfully, but the payment isn’t going through and I’m getting a “address is invalid” error(tried different addresses) 
This is the how the error on the server looks like
`Started POST "/solidus_paypal_braintree/transactions" for 127.0.0.1 at 2019-02-14 01:45:11 +0200
Processing by SolidusPaypalBraintree::TransactionsController#create as JSON
  Parameters: {"payment_method_id"=>"7", "transaction"=>{"email"=>"ahmadvsmsouti-buyer@gmail.com", "nonce"=>"436880e7-2097-06c6-5d2b-2ef724c55c91", "payment_type"=>"PayPalAccount", "address_attributes"=>{"first_name"=>"Ahmad", "last_name"=>"Msouty", "address_line_1"=>"1 E Main St", "address_line_2"=>"Suite 403", "city"=>"Chicago", "state_code"=>"Illinois", "zip"=>"60622", "country_code"=>"US"}}}
Can't verify CSRF token authenticity.
  SolidusPaypalBraintree::Gateway Load (0.7ms)  SELECT  "spree_payment_methods".* FROM "spree_payment_methods" WHERE "spree_payment_methods"."type" IN ('SolidusPaypalBraintree::Gateway') AND "spree_payment_methods"."deleted_at" IS NULL AND "spree_payment_methods"."id" = $1 LIMIT $2  [["id", 7], ["LIMIT", 1]]
  ↳ /Users/AhmadM/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/solidus_paypal_braintree-8b1b1c81e1a0/lib/controllers/frontend/solidus_paypal_braintree/transactions_controller.rb:59
  Spree::Store Load (0.8ms)  SELECT  "spree_stores".* FROM "spree_stores" WHERE ("spree_stores"."url" = $1 OR "spree_stores"."default" = $2) ORDER BY "spree_stores"."default" ASC LIMIT $3  [["url", "localhost"], ["default", true], ["LIMIT", 1]]
  ↳ /Users/AhmadM/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/solidus_paypal_braintree-8b1b1c81e1a0/lib/controllers/frontend/solidus_paypal_braintree/transactions_controller.rb:16
  Spree::Order Load (2.0ms)  SELECT  "spree_orders".* FROM "spree_orders" WHERE "spree_orders"."completed_at" IS NULL AND "spree_orders"."currency" = $1 AND "spree_orders"."guest_token" IS NULL AND "spree_orders"."store_id" = $2 AND "spree_orders"."user_id" IS NULL LIMIT $3  [["currency", "USD"], ["store_id", 1], ["LIMIT", 1]]
  ↳ /Users/AhmadM/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/solidus_paypal_braintree-8b1b1c81e1a0/lib/controllers/frontend/solidus_paypal_braintree/transactions_controller.rb:16
  Spree::Country Load (1.3ms)  SELECT  "spree_countries".* FROM "spree_countries" WHERE "spree_countries"."iso" = $1 LIMIT $2  [["iso", "US"], ["LIMIT", 1]]
  ↳ /Users/AhmadM/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/solidus_paypal_braintree-8b1b1c81e1a0/app/models/solidus_paypal_braintree/transaction_address.rb:32
  Spree::State Load (2.2ms)  SELECT  "spree_states".* FROM "spree_states" WHERE "spree_states"."country_id" = $1 AND ("spree_states"."name" ILIKE 'Illinois' OR "spree_states"."abbr" ILIKE 'Illinois') ORDER BY "spree_states"."name" ASC LIMIT $2  [["country_id", 233], ["LIMIT", 1]]
  ↳ /Users/AhmadM/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/solidus_paypal_braintree-8b1b1c81e1a0/app/models/solidus_paypal_braintree/transaction_address.rb:40
  Spree::Country Load (0.2ms)  SELECT  "spree_countries".* FROM "spree_countries" WHERE "spree_countries"."id" = $1 LIMIT $2  [["id", 233], ["LIMIT", 1]]
  ↳ /Users/AhmadM/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/bundler/gems/solidus_paypal_braintree-8b1b1c81e1a0/app/models/solidus_paypal_braintree/transaction_import.rb:10
Completed 422 Unprocessable Entity in 21ms (Views: 0.1ms | ActiveRecord: 7.4ms)
`
I have seen that #195 has had the same problem but didn't see any reply on it yet. 
If anyone has faced this issue and could go around it, That would be a huge help. 
Thanks!

**Comment by zener79** [comment]
It is happening to me also. This seems to be related to `Can't verify CSRF token authenticity` error message.

I messed up a bit with the partials, so it may be my fault...

**Comment by asa644** [comment]
This solved the Can't verify CSRF token authenticity problem, but i'm still getting "Address invalid".

**Comment by jaimelr** [comment]
Is the phone number a required field on your orders?

**Comment by dracmaAgil** [comment]
Hey folks! I'm getting this invalid address error with sandbox enviroment, I have created my business sandbox account in paypal and linked to my braintree sandbox account (all of this is because I want to test in my pc before to deploy to heroku) but I'm still getting this error from hell... Any advice (it's not the phone as an optional value in the web preferences) thanks guys!

**Comment by dracmaAgil** [comment]
hey @asa644, did you have any luck with this error? I'm still getting this error... I set my paypal sandbox with all webhooks checked and all the sandbox settings checked too... IDK why I'm still getting this error

**Comment by dracmaAgil** [comment]
it was a little bit more of "rtfm", just monkey patch address model with number required in false to get the complete paypal flow

**Comment by mdesantis** [comment]
To expand the workaround proposed by @dracmaAgil, create a `app/models/spree/address/optional_phone_decorator.rb` decorator with the following content:

```ruby
module Spree::Address::OptionalPhoneDecorator
  def require_phone?
    false
  end

  Spree::Address.prepend self
end
```

**Comment by mdesantis** [comment]
It seems that is PayPal that has to be configured accordingly to the e-commerce requirements: https://github.com/solidusio/solidus_paypal_braintree#paypal-configuration

**Comment by EduardoGHdez** [comment]
> Adding `protect_from_forgery with: :exception, unless: -> { request.format.json? }` to `SolidusPaypalBraintree::TransactionsController` fixed the issue for me

The correct solution for this problem without compromising security, is in your ajax request send the csrf token value as header.
```

If you are using jquery, just add `= require`
