### ISSUE TITLE
On PayPal payment user shipping address gets set with uncorrect firstname and lastname values if they contain a space

### ISSUE THREAD

**Issue by mdesantis** [solidusio/solidus_paypal_braintree#226]
When a user pays with Braintree PayPal (vault flow), the authorization callback gets parsed by the JavaScript code, and then submitted to server. The PayPal authorization callback provides the shipping address with a single field for the user lastname and firstname, `recipientName`. The client side code tries to infer the firstname and the lastname splitting this `recipientName` by space:

https://github.com/solidusio/solidus_paypal_braintree/blob/73e9a692148126745272f902a9ffece191b66225/app/assets/javascripts/solidus_paypal_braintree/paypal_button.js#L125-L126

The problem is that, if your name is for example `Maurizio De Santis`, the lastname will be set to `Maurizio` and the lastname to `De`, discarding the rest.

What's really wrong to me is that after that this shipping address value is submitted to the server, which updates the shipping address thus setting wrong values. But with the Braintree PayPal vault flow you can't change the shipping address via PayPal, so it's redundant to update it after the authorization call with the values that PayPal provides: the shipping address is the one that is already present on the server.

**Comment by tvdeyen** [comment]
A common issue I am very well aware of personally ;)

Solidus removed the presence validation of `last_name` long time ago. We should continue that work and rename the column to `name` in core and deprecate `last_name`. 

Until then we should just store the full name as `first_name`

**Comment by mdesantis** [comment]
@tvdeyen thank you for the information! so you would suggest to save `recipientName` into `first_name`?

**Comment by tvdeyen** [comment]
Yes

**Comment by kennyadsl** [comment]
What about using https://github.com/basecamp/name_of_person instead?

**Comment by tvdeyen** [comment]
@kennyadsl 

> Presenting names for English-language applications where a basic model of first and last name(s) combined is sufficient. This approach is not meant to cover all possible naming cases, deal with other languages, or even titulations. Just the basics.

:man_shrugging:

**Comment by kennyadsl** [comment]
@tvdeyen Yeah, you are right, nevermind... I'm ok with storing everything in the `first_name`, one day we'll get rid of `last_name` at all.
