### ISSUE TITLE
PayPal button: customize style

### ISSUE THREAD

**Issue by MinasMazar** [solidusio/solidus_paypal_braintree#229]
It would be great to allow PayPal button style customization:

+ [PayPal developer guides](https://developer.paypal.com/docs/archive/checkout/how-to/customize-button/#)
+ [On-the-fly customizer](https://developer.paypal.com/demo/checkout/#/pattern/style)

**Comment by seand7565** [comment]
Looks like this issue was solved and can be closed. 🎉
