### ISSUE TITLE
Refunds not allowed after a PayPal dispute has been resolved

### ISSUE THREAD

**Issue by modded-nate** [solidusio/solidus_paypal_braintree#256]
A customer filed a PayPal dispute prematurely before contacting us for an RMA. The case was resolved and closed in PayPal, but when trying to reimburse while processing the return in Solidus, we received an error "PayPal Refund Transaction with an Open Case Not Allowed (4019)" despite being closed in PayPal.

![image](https://user-images.githubusercontent.com/21340562/80978633-5244d200-8df4-11ea-9efb-7dee749c343f.png)

![image](https://user-images.githubusercontent.com/21340562/80978550-33ded680-8df4-11ea-8f9c-3e8f31a07265.png)

**Comment by seand7565** [comment]
Hi Nate,

Sorry for being late to the party, I just started working on this extension.

This error came from PayPal (through Braintree), and IMO is probably the result of one of these three things:
* The dispute was not updated correctly to closed
* Despite being marked as closed, PayPal doesn't consider it "fully" closed yet
* The error message is incorrect, and PayPal simply doesn't want any API refunds taking place on payments with cases - closed or open. 

This appears to be an issue on either Braintree or PayPals side - I don't think there are any changes we can make to our code to resolve this issue. If this is still an issue for you (I know it's been a while!) I think the next step would be to get in touch with Braintree.

Thanks!

**Comment by kennyadsl** [comment]
Closing, feel free to comment and we'll reopen this.
