### ISSUE TITLE
Make the Venmo button testable from outside US contries

### ISSUE THREAD

**Issue by DanielePalombo** [solidusio/solidus_paypal_braintree#303]
- [ ] Add `force_buyer_country` string [preference](https://github.com/solidusio/solidus_paypal_braintree/blob/master/app/models/solidus_paypal_braintree/gateway.rb#L38-L45) to PaymentMethod.
- [ ] If `force_buyer_country` is present, pass it as [buyer-country](https://developer.paypal.com/docs/business/javascript-sdk/javascript-sdk-configuration/#buyer-country) parameter to the [loadPayPalSDK method](https://github.com/solidusio/solidus_paypal_braintree/blob/e0b5c9ea4c3601b6d7b1e912259f37cbdb95312e/app/assets/javascripts/solidus_paypal_braintree/paypal_button.js#L44-L48)

**Comment by RyanofWoods** [comment]
I think we can close this now @DanielePalombo 🙂

**Comment by DanielePalombo** [comment]
I supposed it would have closed when the related PR was merged.
