### ISSUE TITLE
Payments in backend not working

### ISSUE THREAD

**Issue by tvdeyen** [solidusio/solidus_paypal_braintree#74]
Payments are not working in backend currently:

1. The JS only inits if previous cards are present
2. The Braintree client JS is not loaded/included in the backend

Got a fix in my client app, will provide a PR soon.

**Comment by tvdeyen** [comment]
Here is my current branch: https://github.com/tvdeyen/solidus_paypal_braintree/tree/backend-payments

Lacks of tests, though.

**Comment by isaacfreeman** [comment]
@tvdeyen: I've cherry-picked from your branch and it's working for me here so far. If it's OK with you, I'll continue with adding tests and get a PR up.

**Comment by tvdeyen** [comment]
@isaacfreeman sure, thanks.

**Comment by isaacfreeman** [comment]
@tvdeyen: I think we should be able to close this now.

**Comment by tvdeyen** [comment]
Aight
