### ISSUE TITLE
Respect Spree::Config[:address_requires_state] setting in frontend view rendering

### ISSUE THREAD

**Issue by MobilUser** [solidusio/solidus_paypal_braintree#93]
Respect the shop admin setting in respect to  usage of 'STATE' in address.
 
I did quite a while a pull request but it seems to got rejected or ignored.
For most European shops 'STATE' is not relevant. Right now the current implementation throws an error. Below find my proposed code change.

`    var address = {
      line1: '<%= address.address1 %>',
      line2: '<%= address.address2 %>',
      city: '<%= address.city %>',
      <% if Spree::Config[:address_requires_state] %>
        state: '<%= address.state.name %>',
      <% end %>
      postalCode: '<%= address.zipcode %>',
      countryCode: '<%= address.country.iso %>',
      phone: '<%= address.phone %>',
      recipientName: '<%= "#{address.firstname} #{address.lastname}" %>'
    }`

**Comment by tvdeyen** [comment]
Makes sense. Would you mind to send us a PR?
